apiVersion: batch/v1
kind: Job
metadata:
  name: telemetrygen
  namespace: tracing-system
  labels:
    app: telemetrygen
spec:
  ttlSecondsAfterFinished: 30
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: telemetrygen
        image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:v0.74.0
        args: [traces, --otlp-endpoint=otel-collector:4317, --otlp-insecure, --duration=240s, --rate=4]
