apiVersion: v1
kind: Secret
metadata:
  name: metrics-tempo-s3
  namespace: tracing-system
stringData:
  access_key_id: ${AWS_ACCESS_KEY_ID}  # Set these through your deployment environment
  access_key_secret: ${AWS_SECRET_ACCESS_KEY}
  bucket:
  endpoint: https://s3.us-east-1.amazonaws.com
  # region: us-east-1
type: Opaque
